version: '3.8'
networks:
  private:
    external:
      name: private
  web:
    external:
      name: web

services:
  #----------------------
  #--- FRONTEND SSR -----
  #----------------------
  preprod-frontend:
    image: elmas19/frontend-preprod:2.0.1-rc2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: frontend-preprod
    networks:
      - web
      - private
    user: 0:0
    environment:
        ENV_NAME: preprod
    labels:
      - traefik.enable=true
      - "traefik.http.routers.preprod-frontend.entrypoints=websecure"
      - traefik.http.routers.preprod-frontend.rule=Host(`preprod.dsp-archiweb21-ah-es-ag-hk.fr`)
      - traefik.http.services.preprod-frontend.loadbalancer.server.port=4000
      - "traefik.http.routers.preprod-frontend.tls.certresolver=lets-encr"
    restart: always
